
dataDir: c:/data/vocab/store
downloadDir: c:/data/vocab/download
importDir: c:/data/vocab/import
luceneDir: c:/data/vocab/lucene

logging:
    level: INFO
    appenders:
      - type: file
        archive: false
        currentLogFilename: /home/dropwizard/logs/vocab.log

server:
  requestLog:
    appenders:
      - type: file
        archive: false
        currentLogFilename: /home/dropwizard/logs/vocab-request.log

assets:
    mappings:
        /assets/belgif.png: /favicon.ico
        /assets:  /static
        /dataset: /dataset
    overrides:
        /dataset: /home/dropwizard/download
    mimeTypes:
        ttl: text/turtle
        nt: application/n-triples
        jsonld: application/ld+json

views:
    .ftl:
        template_exception_handler: rethrow
        output_encoding: utf-8
   
